[tox]
requires =
    tox>=4.0
disallow-unknown-environments = true

[pytest]
pythonpath =
    {toxinidir}
    data_governance
testpaths = tests

[coverage:run]
# c1レベルのテスト
branch = true
# pytestコマンドで--covを設定した場合はここを参照する
# カバレッジの対象が増えたら追記する
source =
    data_governance/library/utils/
# カバレッジの対象外を指定する
# テストコードを作成したファイルはomitから削除する
omit =
    data_governance/library/utils/config/*
    data_governance/library/utils/dg_web/*
    data_governance/library/utils/html/*
    data_governance/library/utils/log/*
    data_governance/library/utils/setting/*
    data_governance/library/utils/storage_provider/*
    data_governance/library/utils/cmd.py
    data_governance/library/utils/error.py
    data_governance/library/utils/file.py
    data_governance/library/utils/nb_file.py
    data_governance/library/utils/package.py
    data_governance/library/utils/pdf_metadata.py
    data_governance/library/utils/save.py
    data_governance/library/utils/string.py
    data_governance/library/utils/time_tracker.py
    data_governance/library/utils/vault.py
    data_governance/library/utils/widgets.py

[testenv]
deps =
    -rrequirements-dev.txt
commands =
    pytest tests --cov -vv -s --cov-report=html --cov-report=term-missing {posargs}

[testenv:action]
# .github/workflows/unit_test.ymlで利用
description = "For GitHub Actions"
deps =
    -rrequirements-dev.txt
commands =
    pytest tests --cov -v --cov-report=term-missing {posargs}
