[tox]
disallow-unknown-environments = true

[pytest]
pythonpath = data_governance
testpaths = tests

[coverage:run]
# c1レベルのテスト
branch = true
# pytestコマンドで--covを設定した場合はここを参照する
# カバレッジの対象が増えたら追記する
source =
    data_governance/library/utils/research_flow_provenance

[testenv]
deps =
    -rrequirements-dev.txt
commands =
    pytest tests --cov -vv -s --cov-report=html --cov-report=term-missing {posargs}

[testenv:action]
# .github/workflows/unit_test.ymlで利用
description = "For GitHub Actions"
deps =
    -rrequirements-dev.txt
commands =
    pytest tests --cov -v --cov-report=term-missing {posargs}
