[tox]
envlist =
    py39
    py310
    py311

[pytest]
pythonpath = data_governance
testpaths = tests

[testenv]
deps =
    -rrequirements-dev.txt
commands =
    pytest --cov=data_governance/library/utils/research_flow_provenance tests -vv -s --cov-branch --cov-report=html --cov-report=term-missing {posargs}
